apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
  imageregistry: "https://quay.io/tangt64/"
spec:
  containers:
  - name: nginx
  image: nginx:1.14.2
  ports:
  - containerPort: 80