apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-readiness-probe
  name: kubernetes-readiness-probe-svc
  namespace: defaul
spec:
  ports:
  - name: kubernetes-readiness-probe-port
    port: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort