---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-collection
spec:
  params:
  tasks:
    - name: hello-message
      taskRef:
        name: task-helloworld

    - name: username
      taskRef:
        name: task-username
      runAfter:
        - hello-message
      params:
        - name: username
          value: Tekton-User

    - name: install-httpd
      taskRef:
        name: task-httpd
      runAfter:
        - username
      params:
        - name: httpname
          value: nginx

    - name: install-ftp
      taskRef:
        name: task-ftp
      runAfter:
        - username
      params:
        - name: ftpname
          value: proftpd

    - name: install-proxy
      taskRef:
        name: task-proxy
      runAfter:
        - username
      params:
        - name: proxyname
          value: haproxy

    - name: install-svn
      taskRef:
        name: task-svn
      runAfter:
        - username
      params:
        - name: svnname
          value: svn
