apiVersion: v1
kind: Pod
metadata:
  name: resource-limit
  namespace: limitquota
spec:
  containers:
  - name: nginx-limit
    image: nginx
    resources:
      requests:
        memory: "10Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "200m"
---
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-small
    namespace: limitquota
  spec:
    hard:
      cpu: "150"
      memory: "200Mi"
      pods: "2"