apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: limit-pod-1
  name: limit-pod-1
spec:
  containers:
  - image: nginx
    name: limit-pod-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}