- name: install APM service
  hosts: webserver:dbserver:php

  vars_files:
    - vars/apm_packages
    - vars/common_package

  tasks:
  - name: check to hostname by facts
    debug:
      var: "{{ ansible_hostname }}"

  - name: check to hostname by hostname
    command: hostname
   
  - name: check to hostname by inventory
    debug
      var: "{{ ansible_inventory }}"

  - name: install to APM package on {{ ansible_inventory }} --> ansible_hostname
    package:
      name: "{{ apm_package }}"
      state: "{{ pkg_state }}"
    become: true

  - name: enabled and started to APM service
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    ignore_errors: yes
    loop:
     - "{{ apm_package }}"
    become: true
