- name: init to kubernetes master node {{ inventory_hostname }}
  command: kubeadm init --apiserver-advertise-address="{{ k8s_api_address }}" --cri-socket="{{ k8s_cri_socket }}" --pod-network-cidr="{{ k8s_pod_net }}" --service-cidr="{{ k8s_pod_net }}"

- name: create the .kube directory on user
  file:
    path: /root/.kube/
    state: directory

- name: copy the kubernetes config and certification onto user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
  remote_src: yes

- name: create kubeadm token with command
  command: kubeadm token create --print-join-command
  register: k8s_adm_token
