- name: delete to all of crio repository files
  file:
    path: /etc/yum.repos.d/{{ item }}
    state: absent
  ignore_errors: yes
  loop:
    - crio-libcontainer-stable-repository.repo
    - crio-stable-repository.repo
    - k8s-repository.repo
    
- name: copy crio the repository files to /etc/yum.repos.d/
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}.repo"
  loop:
    - rhel8-crio-stable-repository
    - rhel8-crio-libcontainer-stable-repository

- name: install the crio runtime package
  package:
    name: cri-o
    state: latest
