---
- hosts: all
  roles:
    - { role: web, when: "ansible_hostname in groups['web']" }
    - { role: db, when: "ansible_hostname in groups['db']" }
    - { role: firewall }
#    - role: web
#      when: ansible_hostname in groups['web']
