---
- name: web project playbook
  hosts: web

  tasks:
    - name: install a httpd package
      package:
        name: httpd
        state: present
    - name: start and enable to the httpd service
      systemd:
        name: httpd
        state: started
        enabled: true    ## yes

- name: db project playbook
  hosts: db

  tasks:
    - name: install a db package
      dnf:     ## module
        name: "{{ item }}"
        state: present
      loop:    ## plugin
        - mariadb-server
        - mariadb
        - mariadb-client
      ignore_errors: yes

    - name: start and enable to the mariadb service
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - mariadb
        - mariadb-server
        - mysql
        - mysql-server
      ignore_errors: true

- name: web/db firewalld service
  hosts: all

  tasks:
    - name: open to the httpd and mariadb service to each server
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
      loop:
        - http
        - https
        - mysql
