---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-username
spec:
  params:
    - name: username
      type: string
      default: "CHOI GOOKHYUN"
  steps:
    - name: show-username
      image: quay.io/centos/centos:stream9
      script: |
        #!/usr/bin/env bash
        echo $(params.username)
