---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-ftp
spec:
  params:
    - name: ftpname
      type: string
      default: vsftpd
  steps:
    - name: install-ftp
      image: quay.io/centos/centos:stream9
      script: |
        #!/usr/bin/env bash
        echo "install ftp package"
        dnf install $(params.ftpname) -y
