---
- hosts: all

  tasks:
  - copy:
      src: "{{ item }}"
      dest: /tmp/
    loop:
      - KT-Cloud-Gluster.repo
      - KT-Cloud-OpenStack-antelope.repo
      - KT-Cloud-registries.conf
    ignore_errors: true
