---
- hosts: varhosts
  tasks:
    - name: Show the control welcome message
      debug:
        msg: "{{ message }}"      ## Hello blah blah
    - name: Show the storage interface
      debug:
        msg: "{{ storage_interface }}"
    - name: Show the eth0 interface
      debug:
        msg: "{{ ansible_facts.eth0.ipv4.broadcast }}"
      register: save_brod_addr
    - name: Show the hostname
      debug:
        msg: "{{ ansible_facts.hostname }}"
    - name: Show the fqdn
      debug:
        msg: "{{ ansible_facts.fqdn }}"
