- name: install the firewalld package
  package:
    name: firewalld
    state: "{{ pkg_state }}"

- name: install containerd package on {{ inventory_hostname }}
  package:
    name: containerd.io
    state: "{{ pkg_state }}"

- name: install kubernetes packages on {{ inventory_hostname }}
  yum:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
    disable_excludes: all
  loop:
    - kubelet
    - kubeadm
    - kubectl
