apiVersion: v1
kind: Pod
metadata:
  name: liveness-readiness-nginx
spec:
  containers:
  - name: liveness-readiness-nginx
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10        
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10