- name: start and enabled to the firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: disabled_firewalld|bool

- name: start and enabled to {{ runtime_type }}.service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
  #when: "{{ runtime_type }} == containerd.io"

- name: start kubelet.service on {{ inventory_hostname }}
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: restart systemd-modules-load.service
  systemd:
    name: systemd-modules-load
    state: restarted
