---
- name: remove a httpd package on {{ inventory_hostname }}
  package:
    name: httpd
    state: absent
- name: install a httpd package on {{ inventory_hostname }}
  package:
    name: httpd
    state: latest
- name: copy the welcome.html to {{ inventory_hostname }}
  copy:
    content: "Hello an automation world"
    dest: /var/www/html/welcome.html
- name: enable and start the httpd service
  service:
    name: httpd
    state: started
    enabled: true
