---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: using-results
spec:
  results:
    - name: message
      description: Message to be shared
  steps:
    - name: write
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        echo "Secret Message" | base64 > $(results.message.path)
        ls -al /tekton/results/

    - name: read
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        echo $results.message.path
        echo $(results.message.path)
        cat $(results.message.path)
        cat /tekton/results/message
