- hosts: all

  tasks:
  - name: SELinux
    selinux:
      policy: targeted
      state: permissive

  - name: install the firewalld package
    package:
      name: firewalld
      state: present

  - name: start and enabled to the firewalld
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: add the kubernetes ports to firewalld {{ inventory_hostname }}
    firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
    loop:
      - 6443
      - 10240

  - name: copy a kernel module loadup config file
    copy:
      src: files/k8s-modules.conf
      dest: /etc/modules-load.d/k8s-modules.conf

  - name: restart systemd-modules-load.service
    systemd:
      name: systemd-modules-load
      state: restarted

  - name: copy a kernel parameter config file for iptables(nftables)
    copy:
      src: files/99-k8s.conf
      dest: /etc/sysctl.d/99-k8s.conf

  - name: apply the kernel parameter on {{ inventory_hostname }} 
    command: sysctl -p --system

  - name: copy a kubernete/containerd repository file for YUM(dnf-3)
    copy:
      src: files/{{ item }}
      dest: /etc/yum.repos.d/{{ item }}
    loop:
      - kubernetes.repo
      - containerd.repo

  - name: install containerd package on {{ inventory_hostname }}
    package:
      name: containerd.io
      state: present

  - name: regenerate to containerd.io config.toml
    command: containerd config default > /etc/containerd/config.toml

  - name: start and enabled to containertd.service
    systemd:
      name: containerd
      state: started
      enabled: yes

  - name: install kubernetes packages on {{ inventory_hostname }}
    yum:
      name: "{{ item }}"
      state: present
      disable_excludes: all
    loop:
      - kubelet
      - kubeadm
      - kubectl

  - name: start kubelet.service on {{ inventory_hostname }}
    systemd:
      name: kubelet
      state: started
      enabled: yes









