apiVersion: v1
kind: Pod
metadata:
  name: lab-test-init-httpd
  namespace: lab-test-initcontainer
  labels:
    type: init-container
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
      - containerPort: 80
    volumeMounts:
      - name: workdir
        mountPath: /usr/local/apache2/htdocs/
  initContainers:
  - name: install
    image: busybox:1.28
    command:
      - wget 
      - "-O"
      - "/work-dir/index.html"
      - http://example.com
    volumeMounts:
      - name: workdir
        mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
    - name: workdir
      emptyDir: {}