---
- name: Copy RPM repositories files
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
  loop:
    - KT-Cloud-Gluster.repo
    - KT-Cloud-OpenStack-antelope.repo

- name: Container repository file
  copy:
    src: "{{ item }}"
    dest: /etc/containers/registries.conf
  loop:
    - KT-Cloud-registries.conf

- name: Copy policy.json file
  copy:
    src: "{{ item }}"
    dest: /etc/containers/policy.json
  loop:
    - policy.json
