apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-nginx-test
  name: deploy-nginx-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-nginx-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-nginx-test
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}