---
- hosts: all

  remote_user: ansible
  become: true
  become_method: sudo

  pre_tasks:
    - name: updates all of packages
      package:
        name: "*"
        state: latest
  tasks:
    - name: install a vsftpd package
      package:
        name: vsftpd
        state: latest
  post_tasks:
    - name: start and enable the vsftpd service
      systemd:
        name: vsftpd
        state: started
        enabled: true
