- hosts: localhost
  vars_prompt:
  - name: username
    prompt: Put down your name
    private: no

  - name: password
    prompt: Put your password
  
  - name: nic_name
    prompt: put the NIC card name
    default: "ens4"

  tasks:
  - name: print all prompts
    debug:
      msg: "{{ item }}"
    loop:
      - "{{ username }}"
      - "{{ password }}"
      - "{{ nic_name }}"

