apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx-app
spec:
  replicas: 3
  selector:
    app: rc-nginx-app
  template:
    metadata:
      name: rc-nginx-app
      labels:
        app: rc-nginx-app
    spec:
      containers:
      - name: nginx
        image: gcr.io/nginx:latest
        ports:
        - containerPort: 80