apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: origin-net-policy
spec:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              project: remote-net-policy
        - podSelector:
            matchLabels:
              role: www