- name: verify to all services
  hosts: all:!php

  tasks:
  - name: run to  service check block 
    block:
    - name: check to httpd service
      systemd:
        name: httpd
        state: restarted
    - name: check to mariadb service
      systemd:
        name: mariadb-server
        state: restarted
    rescue:
    - name: delete to httpd service
      package:
        name: httpd
        state: absent
    - name: delete to mariadb service
      package:
        name: mariadb-server
        state: absent
    always:
    - debug:
        msg: "Done"
