apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: debug-lab
  name: debug-lab
  namespace: lab-test-debug
spec:
  replicas: 2
  selector:
    matchLabels:
      app: debug-lab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debug-lab
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}