- name: copy to the hosts file to {{ inventory_hostname }}
  copy:
    src: hosts
    dest: /etc/hosts

- name: copy to the kernel parameter file to {{ inventory_hostname }}
  copy:
    src: k8s-kernel-para.conf
    dest: /etc/sysctl.d/99-k8s-para.conf

- name: copy to the kernel module file to {{ inventory_hostname }}
  copy:
    src: k8s-modules.conf
    dest: /etc/modules-load.d/99-k8s-modules.conf

