apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: svc-nginx
  name: svc-nginx
  namespace: svc-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svc-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}