apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apache-alpine
  name: apache-alpine
  namespace: lab-test-pod
spec:
  containers:
  - image: httpd:alpine
    name: apache-alpine
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}