apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  namespace: lab-test-pvpvc
  labels:
    type: pvc-pod
spec:
  volumes:
    - name: lab-pv-storage
      persistentVolumeClaim:
        claimName: lab-pvc
  containers:
    - name: volume-pod
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: lab-pv-storage