apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv
  namespace: lab-test-pvpvc
  labels:
    type: local-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/local-pv"
