apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-pvc
  namespace: lab-test-pvpvc
  labels:
    type: local-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi