---
# tasks file for calico
- block:
  - name: copy calico YAML
    copy:
      src: tigera-operator.yaml
      dest: /tmp/tigera-operator.yaml

  - name: apply calico YAML
    command: kubectl create -f /tmp/tigera-operator.yaml

  - name:
    pause: 10

  - name:
    command: kubectl get pods -n calico 
    register: is_running_calico

  - fail:
      msg:
    when: "failed" in is_running_calico 
  resuce:
    - name: 
      command: kubectl delete -f /tmp/tigera-operator.yaml
    - name: 
      command: kubectl create -f /tmp/tigera-operator.yam
