---
- hosts: all

  vars:
    enabled_httpd: false
    enabled_vsftpd: true
  roles:
    - {role: httpd, when: enabled_httpd}
    - {role: vsftpd, failed_when: enabled_vsftpd}

  tasks:
    - systemd:
        name: httpd
        state: restarted
      register: result_svc_error
      ignore_errors: true

    - package:
        name: httpd
        state: absent
      failed_when: result_svc_error
      ignore_errors: true




